services:
  core_app:
    build: .
    container_name: core_app
    command: bash -c "python3 ./manage.py makemigrations && python3 ./manage.py migrate && python3 ./manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - website-network
      - core-network
    depends_on:
      core_db:
        condition: service_healthy
  core_db:
    image: postgres:16
    container_name: core_db
    restart: always
    volumes:
      - core_db:/var/lib/postgresql/data/
    networks:
      - core-network
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  core_db:

networks:
  website-network:
    name: website_network
  core-network:
    name: core_network

