include:
  - ./backend/friends/docker-compose.yml
  # - ./backend/users/docker-compose.yml
  # - ./backend/history/docker-compose.yml

services:
  nginx:
    build: ./backend/nginx
    container_name: nginx
    restart: always
    volumes:
     - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8443:8443"
    networks:
      - website-network
    depends_on:
      - friends_app
      # - users_app
      # - history_app
  vault:
    build: ./backend/vault
    container_name: vault
    command: sh -c 'sh /vault_init.sh'
    restart: always
    environment:
      VAULT_ADDR: https://0.0.0.0:8200
      VAULT_CACERT: "/vault/tls/vault.crt"
      VAULT_API_ADDR: https://0.0.0.0:8200
    volumes:
      - private-volume:/vault/file
      - ./backend/vault/vault_init.sh:/vault_init.sh
      - ./backend/vault/data/:/vault/env
    cap_add:
      - IPC_LOCK
    networks:
      - website-network
      - vault-network
    ports:
      - "8200:8200"

volumes:
  private-volume: