include:
  - ./backend/friends/docker-compose.yml
  - ./backend/users/docker-compose.yml
  - ./backend/history/docker-compose.yml

services:
  nginx:
    build: ./backend/nginx
    container_name: nginx
    restart: always
    volumes:
     - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./backend/nginx/cert/nginx.crt:/etc/ssl/certs/nginx.crt
     - ./backend/nginx/cert/nginx.key:/etc/ssl/private/nginx.key
     - ./backend/nginx/cert/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - "8443:8443"
    networks:
      - website-network
    depends_on:
      - friends_app
      - users_app
      - history_app
