include:
  - ./backend/friends/docker-compose.yml
  - ./backend/users/docker-compose.yml
  - ./backend/history/docker-compose.yml

services:
  nginx:
    build: ./backend/nginx
    container_name: nginx
    restart: always
    volumes:
     - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8443:8443"
    networks:
      - website-network
    depends_on:
      - friends_app
      - users_app
      - history_app
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
    volumes:
      - private-volume:/vault/file
      - ./backend/vault/config.hcl:/vault/config/config.hcl
      - ./backend/vault/vault_init.sh:/usr/local/bin/vault_init.sh
    cap_add:
      - IPC_LOCK
    command: server
    networks:
      - website-network
    ports:
      - "8200:8200"

volumes:
  private-volume:
