services:
  stats:
    build: .
    container_name: stats
    command: bash -c "python3 ./django/vault/vault_init.py"
    restart: always
    environment:
      - VAULT_DATABASE_NAME=stats_db
      - REQUESTS_CA_BUNDLE=/usr/src/app/vault/vault.crt
    volumes:
      - .:/usr/src/app/django
      - ../vault/data:/usr/src/app/vault/
    networks:
      - website-network
      - stats-network
    depends_on:
      stats_db:
        condition: service_healthy
    ports:
      - "8006:8006"
  stats_db:
    build: ./postgre
    container_name: stats_db
    restart: always
    volumes:
      - stats_db:/var/lib/postgresql/data/
    networks:
      - stats-network
      - vault-network
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_ROLE=${DB_ROLE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  stats_db:

networks:
  website-network:
    name: website_network
  stats-network:
    name: stats_network
  vault-network:
    name: vault_network