### --- Initalize stats of a user ---
POST /api/stats/private/create_statistics_user/ HTTP/1.1
Host: localhost:8006
Content-Type: application/json

{
	"player_id" : "2"
}

### --- retrieve data ---
POST /api/stats/private/add_data_stats/ HTTP/1.1
Host: localhost:8006
Content-Type: application/json

{
	"player_id1" : "1",
	"player_id2" : "2",
	"game" : "flappy",
	"winner" : "2"
}
