### --- Initalize stats of a user ---
POST /api/stats/private/create_statistics_user/ HTTP/1.1
Host: localhost:8006
Content-Type: application/json

{
	"player_id" : "3"
}

### --- Post data Match ---
POST /api/stats/private/post_match_data/ HTTP/1.1
Host: localhost:8006
Content-Type: application/json

{
	"player_id1" : "1",
	"player_id2" : "2",
	"game" : "flappy",
	"winner" : "2"
}

### --- Post data tournament ---

POST /api/stats/private/post_tournament_data/ HTTP/1.1
Host: localhost:8006
Content-Type: application/json

{
	"list_participants" : [1, 2, 3],
	"winner" : "2",
	"game" : "flappy"
}

### --- Get user statistics ---
GET http://localhost:8006/api/stats/2 HTTP/1.1