### sign up + get token
POST https://localhost:8443/api/users/signup/ HTTP/1.1
content-type: application/json

{
	"password" : "123asd456",
	"password2" : "123asd456",
	"username" : "coucou"
}

### create token login
POST https://localhost:8443/api/users/login/ HTTP/1.1
content-type: application/json

{
	"password" : "123asd456",
	"username" : "kfuhgkjd"
}

### logout
POST https://localhost:8443/api/users/logout/ HTTP/1.1
content-type: application/json

{
	"refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNzcwMjkzMywiaWF0IjoxNzI3NjE2NTMzLCJqdGkiOiJhNjBjYzI0NmNhNTg0OWNhYmZiNTE3MzRlZThhMDg2MyIsInVzZXJfaWQiOjF9.A5gr7kGB7Mvi18C-0cCJwUj-Jhxn4jgQCr5J2g2ToJo"
}

### refresh token

POST https://localhost:8443/api/users/token/refresh/ HTTP/1.1
content-type: application/json

{
	"refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNzcwMjc3MCwiaWF0IjoxNzI3NjE2MzcwLCJqdGkiOiJhZWE0MGIzODkzNzY0MDUzYTVjY2MzMzY4NjY4NWU4MSIsInVzZXJfaWQiOjJ9.07_GAHvbmU3SRRf0xEN3xCFlTN2i2i_6OnXq-0JYq2s"
}

### get url api42
GET https://localhost:8443/api/users/url/api42/ HTTP/1.1

### list users
GET https://localhost:8443/api/users/ HTTP/1.1

### update password
PUT https://localhost:8443/api/users/update_password/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI3NDUxMDAxLCJpYXQiOjE3Mjc0NTA3MDEsImp0aSI6IjU5MmQzZjM0OGE0NDRmMzY5NDkwNmE3MjY1YTc2NTY0IiwidXNlcl9pZCI6NX0.QoXtZdV4rc2mO5uKbX4geb_FBfF_8lfJgcOJSCP09uo
content-type: application/json

{
	"old_password": "123asd456",
	"password": "d",
	"password2": "d"
}

### update info
PUT https://localhost:8443/api/users/update_user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI3NjE2ODMzLCJpYXQiOjE3Mjc2MTY1MzMsImp0aSI6IjU3OTkzYTc4YzNlOTQ0ZTdiZGZkNjU5NDNhYTFmYmIyIiwidXNlcl9pZCI6MX0.oA36vMDk7OJTIpspN8bosx4xO2vqyijVe12z-bPmKh8
content-type: application/json

{
	"username": "kfuhgkjd",
	"email": "fghf@fdg.lpd",
	"phone": "0326597845"
}