### sign up
POST https://localhost:8443/api/users/signup/ HTTP/1.1
content-type: application/json

{
	"password" : "123asd456",
	"email" : "a@gmai.com",
	"password2" : "123asd456",
	"username" : "            d     g        "
}

### get url api42
GET https://localhost:8443/api/users/url/api42/ HTTP/1.1

### login
POST https://localhost:8443/api/users/login/ HTTP/1.1
content-type: application/json

{
	"password" : "123asd456",
	"username" : "johanne"
}

### login 2fa
POST https://localhost:8443/api/users/login/2fa/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI3Nzk1MzQ1LCJpYXQiOjE3Mjc3OTUwNDUsImp0aSI6ImM1NDc2OThkZWYzZTRiOTViYWNiMGI5ODk2MDkwMmVhIiwidXNlcl9pZCI6MSwic2NvcGUiOiJ0ZW1wb3JhcnkifQ.tzraF-cR0j5zPtQRQ4U5jv78WCRfRIw21UPXg5OQfSY

{
	"token" : "875419"
}

### refresh token
POST https://localhost:8443/api/users/token/refresh/ HTTP/1.1
content-type: application/json

{
	"refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNzg3MTg2NiwiaWF0IjoxNzI3Nzg1NDY2LCJqdGkiOiI0MGYyMTA0NTdiYTQ0MzVmOWM0YTIwZjYxNWQ1NTM3MyIsInVzZXJfaWQiOjEsInRlc3QiOiJjb3Vjb3UifQ.B9lTi_3R1-f9EnQp6452HVtXLW0MGxhNmxdYvzUxYqw"
}

### logout
POST https://localhost:8443/api/users/logout/ HTTP/1.1
content-type: application/json

{
	"refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNzg4MTA4NSwiaWF0IjoxNzI3Nzk0Njg1LCJqdGkiOiI0MjlhMmQwODA2NGI0ODEyYjllNzg1MmRhMmJmNzFjYSIsInVzZXJfaWQiOjEsInNjb3BlIjoibm9ybWFsIn0.8PYkmTdAj1u3YePcvhVTeXtbGMy6HCwyJJLr28DWP9E"
}

### update password
PUT https://localhost:8443/api/users/update/password/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI3NDUxMDAxLCJpYXQiOjE3Mjc0NTA3MDEsImp0aSI6IjU5MmQzZjM0OGE0NDRmMzY5NDkwNmE3MjY1YTc2NTY0IiwidXNlcl9pZCI6NX0.QoXtZdV4rc2mO5uKbX4geb_FBfF_8lfJgcOJSCP09uo
content-type: application/json

{
	"old_password": "123asd456",
	"password": "d",
	"password2": "d"
}

### update user
PUT https://localhost:8443/api/users/update/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI3Nzk1MzQ1LCJpYXQiOjE3Mjc3OTUwNDUsImp0aSI6ImM1NDc2OThkZWYzZTRiOTViYWNiMGI5ODk2MDkwMmVhIiwidXNlcl9pZCI6MSwic2NvcGUiOiJ0ZW1wb3JhcnkifQ.tzraF-cR0j5zPtQRQ4U5jv78WCRfRIw21UPXg5OQfSY
content-type: application/json

{
	"username": "johanne",
	"email": "fghf@fdg.lpd",
	"phone": "0326597845"
}

### update 2fa
POST https://localhost:8443/api/users/update/2fa/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI3Nzk1MzQ1LCJpYXQiOjE3Mjc3OTUwNDUsImp0aSI6ImM1NDc2OThkZWYzZTRiOTViYWNiMGI5ODk2MDkwMmVhIiwidXNlcl9pZCI6MSwic2NvcGUiOiJ0ZW1wb3JhcnkifQ.tzraF-cR0j5zPtQRQ4U5jv78WCRfRIw21UPXg5OQfSY

{
	"2fa_status": "on"
}

### list users
GET https://localhost:8443/api/users/ HTTP/1.1