# {
# 	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyODMxMzMyMSwiaWF0IjoxNzI4MjI2OTIxLCJqdGkiOiJjM2UwNzFhNGM5MGU0YzFjYTI3N2UxNzliZDJmOTA3ZiIsInVzZXJfaWQiOjIsInNjb3BlIjoibm9ybWFsIn0.ohHypccmxyg-t641nJdAoHeAOs8g-8kObFrFjkxJvfw",
# 	"access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MjI3ODIxLCJpYXQiOjE3MjgyMjY5MjEsImp0aSI6ImJiMTc4MmNmNWYwMjRhMjViZDQwZjRjMzNlM2M4NjI4IiwidXNlcl9pZCI6Miwic2NvcGUiOiJub3JtYWwifQ.uTL6qXuPc9Sjet-2_FZyS0b_-azBKyueivp4cuO3ejE"
# }
### sign up
POST https://localhost:8443/api/users/signup/ HTTP/1.1
content-type: application/json

{
	"username" : "coucou",
	"password" : "123asd456",
	"password2" : "123asd456",
	"email" : "J@gmai.coM",
	"phone" : "+33659482658"
}

### get url api42
GET https://localhost:8443/api/users/url/api42/ HTTP/1.1

### login
POST https://localhost:8443/api/users/login/ HTTP/1.1
content-type: application/json

{
	"password" : "123asd456",
	"username" : "coucou"
}

### login 2fa
POST https://localhost:8443/api/users/login/2fa/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MjE5ODQ1LCJpYXQiOjE3MjgyMTk1NDUsImp0aSI6IjVjZWJiMmMzYTQ2NDRlMGY4ZmJkOGQ5NWJkODViODUxIiwidXNlcl9pZCI6Miwic2NvcGUiOiJ0ZW1wb3JhcnkifQ.cAbXWrRd1VdvnTrYPnaC9StTxJbZdxA1Az4NEUg90ew

{
	"token" : "536118"
}

### refresh token
POST https://localhost:8443/api/users/token/refresh/ HTTP/1.1
content-type: application/json

{
	"refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyODMyMTQwNCwiaWF0IjoxNzI4MjM1MDA0LCJqdGkiOiJjYTZkYmQ4MWQ3Y2U0MDg5OGRlZWQ2MWQ2OWQ0YmViNiIsInVzZXJfaWQiOjEsInNjb3BlIjoibm9ybWFsIn0.bFtVWHzJqIF9E92dVZCzKgPORNoj6G5STZE4aFcS6N4"
}


### logout
POST https://localhost:8443/api/users/logout/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MDcxODYzLCJpYXQiOjE3MjgwNzA5NjMsImp0aSI6ImRjOWQ4N2FmYmM0MTRlNzhhMzAxMDM5ZTJiODk3MjFhIiwidXNlcl9pZCI6Miwic2NvcGUiOiJub3JtYWwifQ.8lIxGL1ZLYdlq1Zbqw4K0XcGdwlnoNsAUTgd0DczkNQ

{
	"refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyODE1NzM2MywiaWF0IjoxNzI4MDcwOTYzLCJqdGkiOiI4OThmMmFkMDY2Y2E0OTUxOWY1YzlkMTJiOTdkODcwOSIsInVzZXJfaWQiOjIsInNjb3BlIjoibm9ybWFsIn0.Kq2fhQPXDsNWjwuzKN8TlDnAfYUvkLQy7Y6sG-oZdUY"
}

### update password
PUT https://localhost:8443/api/users/update/password/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI3ODk5NTYxLCJpYXQiOjE3Mjc4OTg2NjEsImp0aSI6IjhjNGRkYjhhZDE0MzRhMjQ4Y2RkNDYwMjViZDhjMTAzIiwidXNlcl9pZCI6MSwic2NvcGUiOiJub3JtYWwifQ.WzXbjcVJXQHfAnvGI4Dm4INnJnElDfsXAzYxlOXYVnc
content-type: application/json

{
	"old_password": "123asd456",
	"password": "dvv",
	"password2": "d"
}

### update user
PUT https://localhost:8443/api/users/update/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MzAzMjc4LCJpYXQiOjE3MjgzMDI5NzgsImp0aSI6ImExMDZiNjU5YzA2NTRlNWM5NDdjNmFhNzFlNzVlMjVhIiwidXNlcl9pZCI6MjIsInNjb3BlIjoibm9ybWFsIn0.sBlzgo7NKFOjSugN5DYztFx3eRtqMdsdvIOaKtPnguc
content-type: application/json

{
	"username": "coucou",
	"email": "fghf@fdg.ds",
	"phone": "0326597845",
	"pin": "4"
}

### update 2fa
PUT https://localhost:8443/api/users/update/2fa/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MjM1MzI1LCJpYXQiOjE3MjgyMzUwMDQsImp0aSI6ImJjZjFlZDEzM2IzNjRhODBiODc3YzQyZjVmMGU0MDE1IiwidXNlcl9pZCI6MSwic2NvcGUiOiJub3JtYWwifQ.cU6GDTekE-dutHgQYss6VXQBUKqDvHdJqIS9UqZVHwU

{
	"2fa_status": "on"
}

### validate 2fa
PUT https://localhost:8443/api/users/update/2fa/validation/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MjE5ODQ1LCJpYXQiOjE3MjgyMTk1NDUsImp0aSI6IjVjZWJiMmMzYTQ2NDRlMGY4ZmJkOGQ5NWJkODViODUxIiwidXNlcl9pZCI6Miwic2NvcGUiOiJ0ZW1wb3JhcnkifQ.cAbXWrRd1VdvnTrYPnaC9StTxJbZdxA1Az4NEUg90ew

{
	"token" : "712380"
}