### get username from ids
POST http://localhost:8002/api/private/users/retrieve/usernames/
content-type: application/json

{
	"users_id": [-25]
}

### get username from ids
POST http://localhost:8002/api/private/users/retrieve/friends_info/
content-type: application/json

{
	"users_id": [-25, 1, 2, 8, 9, 10]
}

### create new AI
POST http://localhost:8002/api/private/users/new/player/ai/
content-type: application/json


### create new guest
POST http://localhost:8002/api/private/users/new/player/guest/
content-type: application/json

### get type of user
POST http://localhost:8002/api/private/users/retrieve/type/
content-type: application/json

{
	"users_id": [-25, 1, 2, 8, 9, 10]
}

###
POST http://localhost:8002/api/private/users/login/pin/
content-type: application/json

{
	"username": "Guest#6664",
	"pin": ""
}
