@hostname = localhost
@port = 8443
@host = {{hostname}}:{{port}}
@contentType = application/json
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI5NTEyMDQ1LCJpYXQiOjE3Mjk1MTE3NDUsImp0aSI6ImU5OWUzYzEyNWU2MjQyYTM5ZTZlMmNjNmJhMDFiMGUyIiwidXNlcl9pZCI6MSwic2NvcGUiOiJub3JtYWwiLCJ1c2VybmFtZSI6ImhleSJ9.2RwcsBGVO339qR5vDxHXBim8J6nupbDGzXqxfpYowns
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI5MTY2MTMxLCJpYXQiOjE3MjkxNjU4MzEsImp0aSI6IjA3OTM3OTQwMWFiYzQxNmQ4YmJlYzhmZGYwZDM5ZWVmIiwidXNlcl9pZCI6MSwic2NvcGUiOiJub3JtYWwiLCJ1c2VybmFtZSI6ImMifQ.R4YwKkALu57V8wpJeWz3S7KKTIiqeO75EW7qoi75OSU

### create empty tournament
POST https://{{host}}/api/tournaments/create/
Authorization: Bearer {{access_token}}

### add player to tournament
POST https://{{host}}/api/tournaments/player/
Content-Type: {{contentType}}
Authorization: Bearer {{access_token}}

{
	"username": "coucou",
	"pin": "0004",
	"tournament_id": 2
}

### remove player from tournament
DELETE  https://{{host}}/api/tournaments/player/?tournament_id=2&player_id=4
Authorization: Bearer {{access_token}}

### start tournament
POST https://{{host}}/api/tournaments/validate/
Content-Type: {{contentType}}
Authorization: Bearer {{access_token}}

{
	"tournament_id": 7,
	"game": "PG",
	"max_score": -1,
	"max_duration": 56,
	"nb_guest": 8,
	"nb_ai": 10
}

### list guest
GET https://{{host}}/api/tournaments/guests/?tournament_id=5
Authorization: Bearer {{access_token}}

### display matches in round
GET https://{{host}}/api/tournaments/round/?tournament_id=5
Authorization: Bearer {{access_token}}

### start match
POST https://{{host}}/api/tournaments/match/start/
Content-Type: {{contentType}}
Authorization: Bearer {{access_token}}

{
	"tournament_id": 5
}

### finish match
POST http://localhost:8005/api/private/tournaments/match/finish/
Content-Type: {{contentType}}
Authorization: Bearer {{access_token}}

{
	"tournament_id": 5,
	"score1": 1,
	"score2": 2
}