### --- test display hello ---
GET /api/matches/test/hello HTTP/1.1
Host: localhost:8004

### --- test create matches ---
GET /api/matches/test/create_bunk  HTTP/1.1
Host: localhost:8004

### --- test delete all matches ---
GET /api/matches/test/finish_all  HTTP/1.1
Host: localhost:8004

### --- test delete all matches ---
GET /api/matches/test/delete_all  HTTP/1.1
Host: localhost:8004





### --- List matches ---
GET /api/matches/ HTTP/1.1
Host: localhost:8004






### --- new match verified users id ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": 7,
	"player2": 2,
	"game": "PG",
	"max_score": 42,
	"max_duration": 21,
	"tournament_id": -1
}

### --- Error: missing player1 ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	# "player1": 7,
	"player2": 2,
	"game": "PG",
	"max_score": 42,
	"max_duration": 21,
	"tournament_id": -1
}
### --- Error: missing player2  ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": 7,
	# "player2": 2,
	"game": "PG",
	"max_score": 42,
	"max_duration": 21,
	"tournament_id": -1
}
### --- Error: missing game  ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": 7,
	"player2": 2,
	# "game": "PG",
	"max_score": 42,
	"max_duration": 21,
	"tournament_id": -1
}
### --- Error: missing score  ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": 7,
	"player2": 2,
	"game": "PG",
	# "max_score": 42,
	"max_duration": 21,
	"tournament_id": -1
}
### --- Error: missing duration ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": 7,
	"player2": 2,
	"game": "PG",
	"max_score": 42,
	# "max_duration": 21,
	"tournament_id": -1
}
### --- Error: missing tournament_id  ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": 7,
	"player2": 2,
	"game": "PG",
	"max_score": 42,
	"max_duration": 21
	# "tournament_id": -1
}

### --- Error: wrong format player ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": "abc",
	"player2": 2,
	"game": "PG",
	"max_score": 42,
	"max_duration": 21,
	"tournament_id": -1
}
### --- Error: wrong format game ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": 7,
	"player2": 2,
	"game": 12,
	"max_score": 42,
	"max_duration": 21,
	"tournament_id": -1
}
### --- Error: wrong format score ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": 7,
	"player2": 2,
	"game": "PG",
	"max_score": "",
	"max_duration": 21,
	"tournament_id": -1
}
### --- Error: wrong format duration ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": 7,
	"player2": 2,
	"game": "PG",
	"max_score": 42,
	"max_duration": "21m",
	"tournament_id": -1
}
### --- Error: wrong format tournament_id ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": 7,
	"player2": 2,
	"game": "PG",
	"max_score": 42,
	"max_duration": 21,
	"tournament_id": "abc"
}
### --- Error: game acronyme ---
POST /private_api/matches/new_match_verified_id HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"player1": 7,
	"player2": 2,
	"game": "abc",
	"max_score": 42,
	"max_duration": 21,
	"tournament_id": "abc"
}






### --- new match ai ---
POST /api/matches/new/me-ai HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"game": "PG",
	"max_score": 10,
	"max_duration": 60,
	"tournament_id": -1
}
### --- Error: new match ai missing field---
POST /api/matches/new/me-ai HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"game": "PG",
	# "max_score": 10,
	"max_duration": 60,
	"tournament_id": -1
}






### --- new match guest ---
POST /api/matches/new/me-guest HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"game": "PG",
	"max_score": 10,
	"max_duration": 60,
	"tournament_id": -1
}
### --- new match guest missing field---
POST /api/matches/new/me-guest HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"game": "PG",
	"max_score": 10,
	# "max_duration": 60,
	"tournament_id": -1
}






### --- finish match ---
POST /api/matches/finish/39/ HTTP/1.1
Host: localhost:8004
Content-Type: application/json

{
	"score1": 5,
	"score2": 10,
	"duration": 19
}
