# {
# 	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyODMxMzMyMSwiaWF0IjoxNzI4MjI2OTIxLCJqdGkiOiJjM2UwNzFhNGM5MGU0YzFjYTI3N2UxNzliZDJmOTA3ZiIsInVzZXJfaWQiOjIsInNjb3BlIjoibm9ybWFsIn0.ohHypccmxyg-t641nJdAoHeAOs8g-8kObFrFjkxJvfw",
# 	"access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MjI3ODIxLCJpYXQiOjE3MjgyMjY5MjEsImp0aSI6ImJiMTc4MmNmNWYwMjRhMjViZDQwZjRjMzNlM2M4NjI4IiwidXNlcl9pZCI6Miwic2NvcGUiOiJub3JtYWwifQ.uTL6qXuPc9Sjet-2_FZyS0b_-azBKyueivp4cuO3ejE"
# }
### sign up
POST https://localhost:8443/api/users/signup/ HTTP/1.1
content-type: application/json

{
	"username" : "9",
	"password" : "123asd456",
	"password2" : "123asd456",
	"email" : "J@gmai.coM",
	"phone" : "+33659482658"
}

### get url api42
GET https://localhost:8443/api/users/url/api42/ HTTP/1.1

### login
POST https://localhost:8443/api/users/login/ HTTP/1.1
content-type: application/json

{
	"password" : "123asd456",
	"username" : "coucou"
}

### login 2fa
POST https://localhost:8443/api/users/login/2fa/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MjE5ODQ1LCJpYXQiOjE3MjgyMTk1NDUsImp0aSI6IjVjZWJiMmMzYTQ2NDRlMGY4ZmJkOGQ5NWJkODViODUxIiwidXNlcl9pZCI6Miwic2NvcGUiOiJ0ZW1wb3JhcnkifQ.cAbXWrRd1VdvnTrYPnaC9StTxJbZdxA1Az4NEUg90ew

{
	"token" : "536118"
}

### refresh token
POST https://localhost:8443/api/users/token/refresh/ HTTP/1.1
content-type: application/json

{
	"refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyODMyMTQwNCwiaWF0IjoxNzI4MjM1MDA0LCJqdGkiOiJjYTZkYmQ4MWQ3Y2U0MDg5OGRlZWQ2MWQ2OWQ0YmViNiIsInVzZXJfaWQiOjEsInNjb3BlIjoibm9ybWFsIn0.bFtVWHzJqIF9E92dVZCzKgPORNoj6G5STZE4aFcS6N4"
}


### logout
POST https://localhost:8443/api/users/logout/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MDcxODYzLCJpYXQiOjE3MjgwNzA5NjMsImp0aSI6ImRjOWQ4N2FmYmM0MTRlNzhhMzAxMDM5ZTJiODk3MjFhIiwidXNlcl9pZCI6Miwic2NvcGUiOiJub3JtYWwifQ.8lIxGL1ZLYdlq1Zbqw4K0XcGdwlnoNsAUTgd0DczkNQ

{
	"refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyODE1NzM2MywiaWF0IjoxNzI4MDcwOTYzLCJqdGkiOiI4OThmMmFkMDY2Y2E0OTUxOWY1YzlkMTJiOTdkODcwOSIsInVzZXJfaWQiOjIsInNjb3BlIjoibm9ybWFsIn0.Kq2fhQPXDsNWjwuzKN8TlDnAfYUvkLQy7Y6sG-oZdUY"
}

### update password
PUT https://localhost:8443/api/users/update/password/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MzAzNDE0LCJpYXQiOjE3MjgzMDMxMTQsImp0aSI6IjJhOGQ2NWZhMjU4NzRiMTA4MDdjOTQzNTk5NGFhZmUwIiwidXNlcl9pZCI6MjIsInNjb3BlIjoibm9ybWFsIn0.a0e96STtlPjVtiiMIfiFGOhPiQcgrYvRM-RE2JveV9c
content-type: application/json

{
	"old_password": "123asd456",
	"password": "123asd456",
	"password2": "123asd456"
}

### update user
PUT https://localhost:8443/api/users/update/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MzA1MTU4LCJpYXQiOjE3MjgzMDQ4NTgsImp0aSI6ImMxMGQ0Zjk5NTAzMTQ4ZmZhZmY3ODA2Y2UyNDg4YWY4IiwidXNlcl9pZCI6MSwic2NvcGUiOiJub3JtYWwifQ.J2shhvh09iFDrQE8Pwgxvy_BkHOCX3TketTH0a46-I0
content-type: application/json

{
	"username": "coucou",
	"email": "fghf@fdg.ds",
	"phone": "0326597845",
	"pin": "4"
}

###
GET https://localhost:8443/api/users/update/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MzA2MjQ2LCJpYXQiOjE3MjgzMDU5NDYsImp0aSI6ImZiMzU4ZWFiMzlmZDQwMTk4MjcwOTZlYThmMzM0NzliIiwidXNlcl9pZCI6MSwic2NvcGUiOiJub3JtYWwifQ.G2Jd6G4Vwf27OFxhZG7G4PCkdy31cJdG4izN0HDQSAs

### update 2fa
PUT https://localhost:8443/api/users/update/2fa/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MzA4MDYzLCJpYXQiOjE3MjgzMDc3NjMsImp0aSI6IjNiNTc3NWY2M2NkNTRmYzliOGJmOTgyOWNmMzk3NzgwIiwidXNlcl9pZCI6MSwic2NvcGUiOiJub3JtYWwifQ.CDsHko1qNUdZNDAaxT0v7usBQHPeblENOz-q8q9ck5g

{
	"2fa_status": "on"
}

### 
GET https://localhost:8443/api/users/update/2fa/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MzA4MDYzLCJpYXQiOjE3MjgzMDc3NjMsImp0aSI6IjNiNTc3NWY2M2NkNTRmYzliOGJmOTgyOWNmMzk3NzgwIiwidXNlcl9pZCI6MSwic2NvcGUiOiJub3JtYWwifQ.CDsHko1qNUdZNDAaxT0v7usBQHPeblENOz-q8q9ck5g


### validate 2fa
PUT https://localhost:8443/api/users/update/2fa/validation/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MzA4MDYzLCJpYXQiOjE3MjgzMDc3NjMsImp0aSI6IjNiNTc3NWY2M2NkNTRmYzliOGJmOTgyOWNmMzk3NzgwIiwidXNlcl9pZCI6MSwic2NvcGUiOiJub3JtYWwifQ.CDsHko1qNUdZNDAaxT0v7usBQHPeblENOz-q8q9ck5g

{
	"token" : "804775"
}