#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE "$POSTGRES_ROLE" NOINHERIT CREATEROLE CREATEDB;
	GRANT ALL ON SCHEMA public TO "$POSTGRES_ROLE";
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_ROLE";

EOSQL